### ISSUE TITLE
Auto Close Trade

### ISSUE THREAD

**Issue by AlleSchonWeg** [vanduc1102/etoro-helper#1]
Hi,

it is possible to monitor the web ui and a close a position, if the rate fall under a defined value. Like StopLoss and TakeProfit. I ask, because SL and TP are not available for cryptos.
Thank you.

**Comment by vanduc1102** [comment]
hi @AlleSchonWeg ,
thanks for asking.

I can see TP is still available for Cryptos,
I will check for SL.
but i wont promise anything, I can see the function will be harmful if it doesn't work as expected ( 💰 )

**Comment by AlleSchonWeg** [comment]
Hi @vanduc1102 
yes TP is now available. I wrote a script which closes crypto trades: https://github.com/AlleSchonWeg/eToroCloseCryptos
Only tested with virtual...

**Comment by vanduc1102** [comment]
Hi @AlleSchonWeg ,
I don't think I can do the task also it is not practical to use the function.
💰 💰 💰 💰 💰 💰 
Thanks for your time with the issue.
