### ISSUE TITLE
Wrong spreadPercent calculation

### ISSUE THREAD

**Issue by bacca87** [vanduc1102/etoro-helper#2]
Hi,
the spreadPercent calculation in your code is wrong. To get the right value you should divide by the sell price instead of the buy price.

Original code:
`let spreadPercent = (spreadPrice / buyPrice) * 100;`

Fix:
`let spreadPercent = (spreadPrice / sellPrice) * 100;`

**Comment by vanduc1102** [comment]
Thank @bacca87 , i will fix it soon
